### ISSUE TITLE
meta: admin일때 모든 유저의 Token를 가지고 올 수 있는 기능 검토

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1014]

**Comment by khw7096** [comment]
편의성 VS 보안 관점에서 논의해보기
- 지금 당장 2가지 방법중 선택해야하 한다면 보안을 선택할 수 밖에 없지만, 편의성도 중요하기 때문에 장기적으로 회의해보기
- 웹서버를 실행하기 전에 security 레벨을 설정하는 옵션을 만드는 방법있다. 이 방법은 서비스를 사용하는 사용자에게 보안의 범위까지 선택할 수 있도록 하는 방법이다.
- 결국 CSI라는 툴이 여러곳에 전파된다면 결국 편의성 이슈가 나올 수 밖에 없다는 점에서 동의하고 인트라넷 환경에서는 관리자측에서 편리할 수 밖에 없는 기능이라고 생각함.

**Comment by baesy0** [comment]
제 의견을 위에 정리해주어서 고마워요
추가적으로 적을게요.

#### 보안 vs 편의성
보안과 편의성 중 양자택일을 해야한다면 보안이라고 생각해요.

#### 전략 제안
하지만 편의성도 무시할 수 없는 이슈라고 생각해요. 특히 인트라넷 환경인 경우에는 좋은 옵션일 수 있구요.
- 당장은 보안을 위주로 하되
- 장기적인 관점에서 보안레벨을 선택할 수 있도록 만드는 것도 좋을 것 같아요.

#### 제가 주의하는 지점
사용자의 선택으로 넘기려면 판단에 필요한 모든 정보를 줄 수 있어야 한다고 생각해요.(이 옵션을 선택할 경우 어떤 후폭풍이 있을 수 있는지 등등)
그렇기 때문에 충분한 시간을 들여서 준비해야 할 것 같아요.
보안은 특히나 조심스럽게 다뤘으면 좋겠어요

**Comment by khw7096** [comment]
만약 보안 옵션이 생긴다면 /api/validuser RestAPI도 보안모드가 낮을 때 만 작동되어야 한다고 생각합니다. 이 옵션을 이용해서 외부 해커가 수천만번의 테스트로 패스워드를 알아낼 수도 있는 창구이기 때문입니다.

**Comment by baesy0** [comment]
위 전략대로 진행할 거라면
보안에 관련된 모든 기능을 나열하고 분류하는 과정이 필요할 거 같아요.
1. 보안의 관점에서 각 기능을 검토
    - ex)어떤 기능이 보안에 치명적인지, 어떤 기능은 덜 관련되어있는지, 보안모드를 바꿀 경우 영향을 받는 기능은 무엇인지 등등
1. 보안레벨을 몇 단계로 나눌지 토의
1. 각 기능을 보안레벨에 따라 분류

이런 과정이 되지 않을까 싶어요

**Comment by khw7096** [comment]
개인적인 생각으로는 2단계로 분류하되, 추후 세부 보안단계가 생길 수 있으니 bool 형이 아닌 자료구조로 2단계 분류를 설정하고 싶어요. == 미래성

**Comment by baesy0** [comment]
보안 관련 기능 리스트업이 되어야 실질적인 토의가 가능해질 것 같아요.
개발하면서 관련 기능을 발견할 때마다 리스트업하는 과정을 먼저 진행하는 건 어때요?

**Comment by khw7096** [comment]
동의해요.

**Comment by baesy0** [comment]
그럼 검토는 끝났으니 새로운 이슈를 만들고 이 이슈는 닫을게요
