### ISSUE TITLE
user: 삭제 UX 제안

### ISSUE THREAD

**Issue by baesy0** [digital-idea/OpenPipelineIO#1021]

**Comment by baesy0** [comment]
### 1
<img width="249" alt="image" src="https://user-images.githubusercontent.com/40417084/98884675-e2ff1780-24d3-11eb-904b-8d543447c4cf.png">

### 2
<img width="243" alt="image" src="https://user-images.githubusercontent.com/40417084/98884762-07f38a80-24d4-11eb-9a49-2fed313d0b71.png">

**Comment by khw7096** [comment]
2번안이 저는 좋아보여요.(너무 많은 색상이 보이는것이 시각적으로 혼란스러워 보여서요.)

**Comment by baesy0** [comment]
저도 동의해요!
