### ISSUE TITLE
보안모드: 보안과 관련있는 기능 리스트업하기

### ISSUE THREAD

**Issue by baesy0** [digital-idea/OpenPipelineIO#1041]
- 관련 논의: #1014
- 옵션: securitymode

**Comment by khw7096** [comment]
- 인터넷 환경(보안강화) VS 인트라넷 환경(편의성강화)
- /api/validuser  허용
- admin일때 user의 Token을 가지고 오는 기능
- user의 암호화된 패스워드 해쉬코드를 가지고 오는 기능

**Comment by khw7096** [comment]
내부에서 커스텀하게 만든 툴에서 로그인 기능을 구현하는 것이 귀찮기 때문에 Token을 가지고 올 수 있도록 구현하면 수많은 툴에서 로그인을 구현하지 않아도 된다.
리뷰툴을 모사한 툴에서 코멘트를 날릴때 아이디어가 나왔다.
