### ISSUE TITLE
user: 자기 자신의 계정을 삭제하는 경우

### ISSUE THREAD

**Issue by baesy0** [digital-idea/OpenPipelineIO#1047]
현재: not found 화면으로 넘어감

1. 자신의 계정을 지우지 못하게 한다
1. 자신의 계정을 지우면 로그인 화면으로 넘어가게 한다.

**Comment by khw7096** [comment]
만약, 자기가 자기 자신의 계정을 지우면 로그인 화면으로 넘어가도록 하는 것이 좋을 것 같아요.

**Comment by baesy0** [comment]
저도! 그 방향으로 짜볼게요

**Comment by baesy0** [comment]
### 재토론
- 결론: 자신의 계정은 삭제하지 못 하도록 한다.
- 이유: 삭제 권한이 있다는 것은 최고관리자라는 것을 의미한다.. 퇴사 등의 사유로 최고관리자의 계정을 삭제해야 하는 경우, 회사 내 다른 사람이 이 사실을 알고 있을 필요가 있다.

#### case 1. 최고관리자가 다수인 경우.
다른 관리자가 해당 관리자의 계정을 삭제한다.

#### case 2. 최고관리자가 유일한 경우.
차기 관리자에게 인수인계 및 권한을 부여한 후, 인수인계받은 관리자가 해당 관리자의 계정을 삭제한다.

**Comment by baesy0** [comment]
본인의 계정인 경우 삭제버튼이 나타나지 않도록 한다.
