### ISSUE TITLE
Tag입력시 공백이 들어가는지 체크하기.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#1064]

**Comment by baesy0** [comment]
### 이미 존재하는 태그의 앞,뒤,중간에 공백을 추가한 후, 태그를 입력한 경우 뜨는 에러 메세지
<img width="508" alt="image" src="https://user-images.githubusercontent.com/40417084/101429937-5ff0a600-3947-11eb-8999-d37dc58b41e0.png">

### DB API: addTag
https://github.com/digital-idea/csi3/blob/a403f855cad03db52accc18e3a5f8486dce38510/db_item.go#L2660
DB API인 addTag함수에서 공백을 제거하도록 되어 있어요.
공백이 있는 경우 공백을 제거한 후, 중복인지 체크하고 있어서 어떻게 공백이 들어갈 수 있었던건지 궁금해요.

**Comment by khw7096** [comment]
태그 일괄변경 기능에서 들어갔다고 들었는데 그 부분의 코드를 한번 봐볼께요.
