### ISSUE TITLE
shot 정보 수정이후의 페이지 이슈

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#138]
특정 태그나 검색어로 아이템을 검색 한 이후, 어느 한 샷 정보 수정을 하면 이전에 검색한 페이지가 아닌 수정된 샷만 페이지에 나오게 변경이 되었습니다.
여러 아이템을 수정해야하는 관리자 입장에서는 이렇게 변경된 것이 불편하다는 의견입니다.
이전의 csi처럼 수정 이후에도 이전 검색결과 페이지가 나오도록 설정이 가능할까요?

**Comment by khw7096** [comment]
기존 기능은 리다이렉션이 없이 진행된 약간은 버그같은 느낌이었어요. 하지만 원한다면 되돌릴께요.

**Comment by jyub86** [comment]
여러 데이터를 수정해야 하는 분들은 매번 다시 검색해야 하니 번거롭긴 할 것 같아요...

**Comment by khw7096** [comment]
좋아용!

**Comment by jyub86** [comment]
감사합니다~!

**Comment by khw7096** [comment]
자바스크립트를 이용해서 수정버튼을 누를 때, 강제로 히스토리가 (이전, 이전 페이지)로 이동하도록 변경하기.

**Comment by khw7096** [comment]
Ref

https://www.w3schools.com/jsref/met_his_go.asp

**Comment by khw7096** [comment]
v3.0.5 로 버전을 올림. 릴리즈 완료.
