### ISSUE TITLE
CSI 검색 이슈

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#148]
태그 검색 시의 이슈입니다.
태그를 클릭 했을 때의 검색은 문제 없지만, "#태그" 검색 시 검색이 되지 않는 문제가 있습니다.

**Comment by khw7096** [comment]
이것 역시 tag: 으로 바꿀께요.
이유는 #은 url 파서문자로 사용할 수 없어서이기도 해요.

**Comment by jyub86** [comment]
옙!

**Comment by khw7096** [comment]
현재는 `tag:검색어` 형태로 검색을 하면 태그가 검색이 되어용. 태그를 클릭시에도 `tag:검색어` 형태로 입력이 되도록 바꿀께요.

**Comment by khw7096** [comment]
done.
