### ISSUE TITLE
프로젝트 변경 권한 레벨 변경 요청

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#149]
현재 팀의 리드의 권한은 AccessLevel 4로 설정되어 있습니다.

프로젝트 Edit 권한이  level 5 이상으로 되어 있는데, 4로 변경 요청 드립니다.

**Comment by khw7096** [comment]
넵. 내일 출근하면~ 바로 고고~!

**Comment by khw7096** [comment]
33e4034
