### ISSUE TITLE
통계: 전체 샷 프로젝트 어떻게 볼 것인지

### ISSUE THREAD

**Issue by baesy0** [digital-idea/OpenPipelineIO#1725]
- [x] #1727
- [x] 프로젝트 상태를 프로젝트 옆에 표기할 수 있도록 만들기

**Comment by khw7096** [comment]
코드 구현: 먼저 히든 모드로 차트를 그리고 토글 되었을 때 해당되는 프로젝트만 hidden이 false 되는 형태로 구현되면 좋을 것 같다.
