### ISSUE TITLE
프로젝트가 생성될 때 thumbnail폴더 하위에 프로젝트 폴더가 생성될 수 있도록 만들기.

### ISSUE THREAD

**Issue by bae-seoyoung** [digital-idea/OpenPipelineIO#1933]
scanplate 기능 사용시 내부 서버에서 외부서버로 thumbnail을 전송할 때 문제가 발생한다.

**Comment by bae-seoyoung** [comment]
https://github.com/digital-idea/OpenPipelineIO/blob/d987187a7406a92e9c8c9ef443eda0849aa198de/handler_project.go#L62

**Comment by bae-seoyoung** [comment]
업로드 썸네일 api 체크해보기

**Comment by bae-seoyoung** [comment]
uploadthumbnail 함수 체크시 실제 사용되는 함수는 다음과 같다.

```bash
err = os.MkdirAll(path, os.FileMode(permission))
```

다른 원인이 있는지 체크해보기.

**Comment by bae-seoyoung** [comment]
- [ ] 프로젝트가 없는 상태에서 curl 테스트
- [ ] 프로젝트가 있는 상태에서 curl 테스트

**Comment by khw7096** [comment]
```
(?P<name>\w+)_main(?P<other>\w+)_v(?P<version>\w+).(?P<frame>\W\w+)(?P<ext>.\w+)
```

레귤러 익스프레션 이슈였다.
