### ISSUE TITLE
파트너 관리 툴 자료구조 정리

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#201]
- [x] 자료구조 정리

**Comment by khw7096** [comment]
vendor(공급업체) | Partner

- 주소: 
- 아이디: 코드명
- 표기명: 한글표기명
- 사업자등록번호
- 홈페이지:
- 주소
- 설명: 무얼 하는 회사인가?
- 장점(특징): 무엇을 잘하는 회사인가?
- 담당자명:
- 담당자 전화
- 담당자 이메일
- 국가/시간대: 회사가 어느위치인가
- 프로젝트
    - 상태: 아젠다, 계약전 협의, 계약서 작성, 계약금 입금, 중도금1차, 중도금2차, 잔금, 전자세금계산서 요청, 전자세금계산서 완료, 소송
    - 프로젝트: 같이 어떤 프로젝트 하고 있는가?
    - 히스토리: 과거 어떤 프로젝트에서 이슈가 있는가?
    - 계약일: 
    - 종료일: 
    - 버짓: 진행 프로젝트 자금규모 얼마인가?
    - 해외프로젝트인가?(VAT 포함, 미포함)
- ftpID
- ftpPW

**Comment by khw7096** [comment]
메뉴에 추가함.

**Comment by baesy0** [comment]
회사 내부 담당자라면 user에서 골라도 되지 않을까
