### ISSUE TITLE
프로젝트 자료구조에서 상태 중복검색이 가능하도록 기능추가.

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#208]
/api/projects?status=pre,post

형태가 검색되었으면 좋겠다.

현재는 하나의 상태만 지원된다.

**Comment by khw7096** [comment]
인수가 없다면 기본적으로 준비,작업중,백업중 리스트를 가지고 오는 api는 존재한다.

**Comment by khw7096** [comment]
api를 2번 호출하기로 함.
