### ISSUE TITLE
VaildUser API 사용 시 사용할 수 없는 특수문자

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#217]
'&' 문자열이 들어간 패스워드에서 문제가 발생했는데요,
아마도 curl 에서 &을 사용하기 때문인거 같습니다.
('='은 가능하네요...)
혹시.. 위 특수문자를 사용가능하게 만들 수 있는 방법이 있을까요?

**Comment by khw7096** [comment]
방법을 찾아볼께요.

**Comment by khw7096** [comment]
`;` 문자도 테스트 해보기.

**Comment by khw7096** [comment]
0eb38b4
