### ISSUE TITLE
PR 방식으로 개발하면 좋겠습니다.

### ISSUE THREAD

**Issue by kybin** [digital-idea/OpenPipelineIO#309]
roi 개발에 빚을 지고 있으니, csi를 PR을 이용해 개발하면 저도 도울게요.

**Comment by khw7096** [comment]
이 부분은 디지털아이디어 밖에서 개발 되거나.. 금주 기술시연이 일어나지 않는 날에는 PR 형태로 진행할 께요.

내부에서는 PM, 다른 개발자들과 오프라인 리뷰를 하고 있어요.

의견에는 찬성해요.

**Comment by kybin** [comment]
네, 만약 PR로 개발하면 저도 리뷰할게요. 이슈는 닫겠습니다.
