### ISSUE TITLE
썸네일을 선택했을때 보더의 색이 변하게 하기

### ISSUE THREAD

**Issue by kybin** [digital-idea/OpenPipelineIO#310]
현재는 보더 바깥으로 새로운 보더가 생기는데 이보다는 보더의 색만 변하는게 깔금할것 같아요.

물론 중요한 문제는 아닙니다.

**Comment by khw7096** [comment]
829525e

색이 추가되고 픽셀이 밀리지 않도록 함. 상태색을 덮어쓰지 않도록 함.
