### ISSUE TITLE
csi-dev에서 기존 프로젝트의 정보를 조금이라도 수정했을 경우의 문제

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#357]
구조가 변경되어서인지 일부 데이터가 삭제?되는 듯합니다....

api로도 샷 정보를 가져올 수 없고, DB안에서도 task와 작업내용, 수정내용 등의 정보가 날라가네요..;;;

기존 프로젝트와 호환되지 않는다고 전달했는데도 이런 문제가 발생해버렸습니다.....

혹시 dev에서 기존 프로젝트에 접속 못하게 하는 방법이 있을까요?

**Comment by khw7096** [comment]
아예 DB를 나누는 방법은 어때요?

**Comment by khw7096** [comment]
일단 당장 생각나는건 두개가 자료구조가 완전히 달라서.. 과거버전과 호환해서 쓰지 않는것이 가장 좋긴해요.

두번째는 프로젝트가 검색되고 과거 프로젝트명이라면 그 프로젝트를 다시 삭제하는 방법이 떠올라요~!

**Comment by khw7096** [comment]
다른 아이디어: admin setting에 무시할 프로젝트를 입력하고 입력된 프로젝트는 프로젝트 리스트에 나오지 않도록 필터한다.

**Comment by khw7096** [comment]
옵션추가함.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/1149996/70847058-44bd9880-1ea3-11ea-8d04-8bf82f1965ac.png">
