### ISSUE TITLE
org1을 등록할 때, 샷이 아니고 src로 등록이됩니다.

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#379]
SS_0030 이란 샷이 존재하고 plate를 org2로 추가 등록하려고 하는 경우,
org2도 해당 샷에 등록이 되고 또한 **SS_0030이라는 SRC가 추가로 등록됩니다.**

사용한 명령어
    /lustre/INHouse/CentOS/bin/csi3 -add item project TEMP -name SS_0030 -type org2 -scanframe 5 -scantimecodein 00:00:00:00 -scantimecodeout 00:00:00:04 -scanname ops_0220_src1 -platesize 1920x1080 -platein 1001 -plateout 1005 -updateparent

**Comment by khw7096** [comment]
기존 csi3도 모든 스캔이 진행되면 전체가 등록되는 상황이었습니다.
검토결과 회사에서 들어오는 모든 데이터가 등록되는 것이 맞다고 결론 내렸습니다.
