### ISSUE TITLE
여러 Task가 있는 경우 status가 동시에 같이 변경됩니다.

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#394]
예를들어 comp와 mg가 있는 경우, comp 상태를 변경하면 mg상태가 똑같이 따라 변경됩니다.

**Comment by khw7096** [comment]
방금 테스트했을 때는 클라우드 쪽, 개발서버 2개에서는 아직 발생하지 않았어요. 몇번 더 테스트 해볼께요.

**Comment by jyub86** [comment]
해당 테스크의 색은 안변하는데, 우측 메뉴로 들어가서 상태 변경을 하려고 보면 변경되어 있어요!

**Comment by khw7096** [comment]
파이어폭스는 기존 값을 가지고 있다. 체크하기.

**Comment by khw7096** [comment]
80df97d
