### ISSUE TITLE
Task를 처음 등록하면 assign으로 되는 것은 어떨까요?

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#395]
지금은 변경없음으로 되어있는데, 이 상태를 표시하는 색이 따로 없다보니 혼선이 생기는 것 같습니다.

**Comment by khw7096** [comment]
좋아요.

**Comment by khw7096** [comment]
edit 을 눌렀을 때 최초 task를 가지고 오는 getRestAPI를 제작하고 가지고 온 값으로 모달을 채우는 방식으로 변경하기.

**Comment by khw7096** [comment]
이 기능을 위해서 /api/task 제작완료.

**Comment by khw7096** [comment]
80df97d
