### ISSUE TITLE
어셋을 추가할 때 언더바를 사용하고 싶습니다.

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#407]
제작부에서는 'asset_a'  와 같은 네이밍을 사용하고 싶다고 합니다.

현재 언더바는 어셋이름으로 사용할 수 없게 되어 있습니다.

추가가 가능할까요?

**Comment by khw7096** [comment]
네 추가해볼께요.

**Comment by khw7096** [comment]
f6fb262
