### ISSUE TITLE
윈도우 머신에서 메일을 썬더 버드로 연결이 가능할까요?

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#430]
CSI 에서 메일 보내기 기능을 윈도우 머신에서도 썬더버드로 연결이 가능할까요?

**Comment by khw7096** [comment]
이 부분은 브라우저 셋팅과 관련이 있을것 같아요. 방법을 찾아봐야겠네요.

**Comment by khw7096** [comment]
https://support.mozilla.org/en-US/kb/make-thunderbird-default-mail-client

**Comment by khw7096** [comment]
위 설정으로 셋팅해 보았다. 안된다. 윈도우즈 머신을 셋팅하고 테스트필요함.

**Comment by khw7096** [comment]
firefox를 사용하면 수정설정이 가능하다.

**Comment by khw7096** [comment]
최신 firefox를 설치하고 해결됨.
