### ISSUE TITLE
asset을 등록 시, 자동 생성 되는 테스크가 없으면 좋겠습니다.

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#432]
예로 env type으로 asset을 생성하면 env와 matte task가 자동으로 생성됩니다.

이러한 기능이 없으면 좋겠다고 합니다.

shot의 경우 comp가 생기는데, 이 기능은 괜찮다고 합니다.

**Comment by khw7096** [comment]
네~!

**Comment by khw7096** [comment]
6204e65
