### ISSUE TITLE
plate를 업데이트 시, Just 초기화 기능

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#433]
플레이트가 org1 등으로 업데이트 된 경우, 기존에 적혀있던 just 정보가 초기화 되어야 하는데,

이 기능 넣어주실 수 있을까요? 만약 코드가 복잡해진다면, 해당 코드를 scanpub에 추가하는 방법도 있습니다.

어떤 방법이 더 좋을 지, 의견 부탁드립니다!

**Comment by khw7096** [comment]
가능할듯해요.

**Comment by khw7096** [comment]
c4be77d
