### ISSUE TITLE
레퍼런스 등록 시 검색되지 않는 제목이 있습니다

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#457]
예) 4th_ani_0121

숫자 없이 문자로만 되어 있는 제목은 검색 가능한데 숫자+영문 등으로 되어 있는 제목이 검색되지 않는 것 같습니다.

**Comment by khw7096** [comment]
98deec6

**Comment by khw7096** [comment]
reference 는 원래 검색에 없었음.
