### ISSUE TITLE
restAPI 확인 한번 부탁드립니다.

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#458]
오늘 setThummov 등, 몇몇 API 작동이 되지 않습니다. 혹시, 최근에 변경된 부분이 있나요?

**Comment by khw7096** [comment]
메일 부분만 하루전에 변경되었어요. 저도 setThummov 함수를 체크해볼께요.

**Comment by khw7096** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/1149996/73326245-dbe48100-4294-11ea-88b5-17d8443f5d7e.png">

소문자로 선언되어있는데 대문자로 보냈나요?

**Comment by khw7096** [comment]
현 csi에는 문제없다. 과거 csi는 문제가 있다. 하지만 자료구조의 변동이 없기 때문에 현 csi의 restAPI를 이용해서 바꾸어도 된다.
