### ISSUE TITLE
api 추가 요청

### ISSUE THREAD

**Issue by jyub86** [digital-idea/OpenPipelineIO#486]
저희 API 몇가지만 요청 드립니다. 어셋에 관련된 API입니다.

1. Asset - Shot과 같이 어셋의 정보를 딕셔너리 형태로 반환한다.

2. Assets : Shots와 같이 어셋 리스트를 반환한다.

**Comment by khw7096** [comment]
네~!

**Comment by khw7096** [comment]
fc3e7ce
