### ISSUE TITLE
shotname 자유도 올리기.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#551]
현재는 SS_0010 구조이다. 이 형식이 아니더라도 샷이 생성되면 좋다.
- tQCS, StudioG, RD101

**Comment by baesy0** [comment]
허용 문자
- 영어 소문자
- 영어 대문자
- 숫자
- 언더바
- 작대기

**Comment by baesy0** [comment]
SS_0010 -> seq:  SS, cut: 0010 값이 자동으로 들어가는 구간이 존재한다. 조건이 맞을 때만 값이 들어갈 수 있도록하기.

조건: 마디(공백, 언더바, 작대기)를 기준으로 seq, cut 분류.
- SS 0010: 분리가 일어난다 적용되면 안된다.=
- SS_0010
- SS-0010
- ss_0010
- ss 0010
- ss-0010
- s0010_c0010: seq:s0010, cut:c0010

**Comment by khw7096** [comment]
StudioG를 셋팅하며 해결함.
