### ISSUE TITLE
가입 시 captcha 입력이 맞는 것 같은데 계속 id가 다르다고 뜹니다!

### ISSUE THREAD

**Issue by dchecheb** [digital-idea/OpenPipelineIO#717]
![captcha](https://user-images.githubusercontent.com/46209590/83613069-39c80300-a5be-11ea-8521-24e0795a8c3a.png)

![Screenshot from 2020-06-03 17-17-14](https://user-images.githubusercontent.com/46209590/83613166-5ebc7600-a5be-11ea-893e-24141c6b0a34.png)

그리고 틀렸다는 알림받고 다시 시도하려고 뒤로가기를 누르면 같은 captcha가 떠요! 이럴 때 새로운 captcha를 받을 수 있는 방법이 있을까요??

**Comment by khw7096** [comment]
캡차는 한번 발급되면 사라지게 되는 코드라서 그래요. 현재는 새로고침을 하고 다시 입력하면 될 것 같아요.

사람들이 귀찮아하면 빨간색 * 표시만 입력해도 가입은 되니.. 가입후 개인정보를 입력하는 것도 좋은 방법이예요.

**Comment by khw7096** [comment]
200260 으로 입력했어야 하니.. 실제로는 틀리게 입력했네요.
