### ISSUE TITLE
user 관련 질문

### ISSUE THREAD

**Issue by dchecheb** [digital-idea/OpenPipelineIO#732]
**- adduser restapi 만드는 거 가능할까요??**
각자 가입하는 방식은 힘들 것 같아서요. 제가 수동으로 다 가입하고 아이디랑 비번 각자 뿌려주려고 했는데요! 보안상으로 좋지 않은 방법일까요??

~~**- user 삭제는 어떻게 하나요?**~~
이건 찾았어요! csi3 명령어랑 flag 이용하면 되는 것 맞겠죠??

**Comment by khw7096** [comment]
네~ 보안상으로 좋지 않지만, 필요한 기능이면 고려할 듯해요.
아마도 생성과정에서 동일한 패스워드를 사용할 확률이 높을 것 같아요.

그래도 필요하다면 만들까요? 이 의견에 대한 채윤님의 생각은?

**Comment by khw7096** [comment]
오프라인 미팅으로 회의함. 좀더 고민을 해보고 다시 알려주기로 함.
