### ISSUE TITLE
csi 이름공모.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#76]
- Contents creation System Integration
- Contents creation system infra
- Contents creation status investigation
- Creative support itself.
- Creation system itself.

결국 다 딱딱한 느낌.

**Comment by khw7096** [comment]
Creation story in inhouse.

**Comment by seonill** [comment]
Captain Seon il

**Comment by jyub86** [comment]
Cocoa Syrup Icecream

**Comment by seonill** [comment]
Call of Silence Industry

**Comment by jyub86** [comment]
creative space ideas

**Comment by jyub86** [comment]
chocolate syrup icecream

**Comment by seonill** [comment]
Caution! Super Incoming

**Comment by kokbee** [comment]
chair shot itself

**Comment by kokbee** [comment]
Chogchoghan Sandwich Icecream

**Comment by jyub86** [comment]
Club Sandwich I like

**Comment by kybin** [comment]
Crime Scene Investigator
CG Scene Investigator?
Creative Scene Investigator
Cooperating Scene Investigator?

**Comment by khw7096** [comment]
더 좋은 이름이 있다면, 툴 이름 자체를 바꾸어도 좋다.

**Comment by khw7096** [comment]
Creation Status Integrator

창작과정통합툴.

이 이름으로 결정. 이름을 지어준 분에게 보답하기.

**Comment by khw7096** [comment]
OpenPipeline.IO 업데이트 완료.
