### ISSUE TITLE
publish: addpublish restapi 에서 윈도우즈 경로 전송해보기.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#894]

**Comment by khw7096** [comment]
`\\\\10.0.0.1\\show\\test\\path`

**Comment by baesy0** [comment]
![image](https://user-images.githubusercontent.com/40417084/92427843-8841fa80-f1c8-11ea-84be-e50962e13fac.png)

전송 테스트 완료.
