### ISSUE TITLE
publish: 윈도우즈 python3에서 보낸 restapi로는 publish가 삭제되지 않는다.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#898]

**Comment by baesy0** [comment]
1. publish가 삭제되지 않는다.
1. restapi로 삭제해보기
1. python3로 삭제해보기

**Comment by baesy0** [comment]
### detailitem.html - remove 버튼
https://github.com/digital-idea/csi3/blob/c417bfa44f6105e107074afb7436d512507d8596/assets/template/detailItem.html#L224
### modal.html - delete 버튼
https://github.com/digital-idea/csi3/blob/c417bfa44f6105e107074afb7436d512507d8596/assets/template/modal.html#L889
### input.js - rmpublish
https://github.com/digital-idea/csi3/blob/c417bfa44f6105e107074afb7436d512507d8596/assets/js/input.js#L1439
### restapiitem.go - handleAPIRmTaskPublish
https://github.com/digital-idea/csi3/blob/3265428bce613207d21994549fe4c7273d0d74e5/restapiItem.go#L7414

**Comment by baesy0** [comment]
1. path가 빈문자열로 전달됨
1. ajax에서 path를 쏘고 있지 않음.
1. 모달창에 hidden으로 path를 가지고 있어야 함
https://github.com/digital-idea/csi3/blob/a9085e47e20621a70d052ca9d3f984007eed1486/assets/template/modal.html#L884
1. 모달창의 hidden값을 설정하는 부분
https://github.com/digital-idea/csi3/blob/c417bfa44f6105e107074afb7436d512507d8596/assets/js/input.js#L1255
1. 인수를 넘겨주려면 recipe에도 path가 있어야 함

**Comment by baesy0** [comment]
Item>Task>Publish
