### ISSUE TITLE
id vs name

### ISSUE THREAD

**Issue by baesy0** [digital-idea/OpenPipelineIO#942]
일관된 규칙의 필요성

**Comment by baesy0** [comment]
### id
- id는 DB에만 있다.
- id를 사용하려면 질의를 해야한다.
- name으로 id를 찾아온다.

### id 구조
name + type

### name
- name으로 id를 찾아온다.

### name을 이용해서 id를 가져오기 어려운 경우
- 재스캔 플레이트에서 작업내용을 작성할 때
- 재스캔 플레이트에서 퍼블리시를 할 때

최종은 id

### curl
curl + os.sys -> 사용가능

**Comment by baesy0** [comment]
퍼즐부분에서의 에러는 정확하지 않은 id값때문이었음.
id가 부여되는 규칙이 명확하게 공유되는 것이 필요해보임

**Comment by khw7096** [comment]
최종적으로는 id가 사용되어야 한다. 샷, 에셋을 하나의 collection에 모아두어야 통계를 쉽게 할 수 있다. name은 중복되는 요소가 많을 수 밖에 없다.

**Comment by khw7096** [comment]
최종적으로는 DB의 오브젝트 id를 쓰는 방향으로 가는것이 좋다고 생각함.
