### ISSUE TITLE
publish: 시간이 같은 publish 경우 usethis가 동시에 설정되는 버그

### ISSUE THREAD

**Issue by baesy0** [digital-idea/OpenPipelineIO#948]
### 현재 조건
<img width="496" alt="image" src="https://user-images.githubusercontent.com/40417084/94091432-300b2980-fe53-11ea-821b-b4883581b9e3.png">
https://github.com/digital-idea/csi3/blob/a639c24ae30fa429d35d18c6700064ddb3ac809a/documents/rest_item.md

**Comment by baesy0** [comment]
### js
https://github.com/digital-idea/csi3/blob/a639c24ae30fa429d35d18c6700064ddb3ac809a/assets/js/input.js#L2953

### REST API
https://github.com/digital-idea/csi3/blob/a639c24ae30fa429d35d18c6700064ddb3ac809a/restapiItem.go#L4165

### DB API
https://github.com/digital-idea/csi3/blob/4adc0ebb46e7713ff98b5dec9841a11ba680ed88/db_item.go#L1745

**Comment by khw7096** [comment]
/api/setpublishstatus 에 path를 추가하기.
