### ISSUE TITLE
review: description이 보일 수 있도록 하기.

### ISSUE THREAD

**Issue by khw7096** [digital-idea/OpenPipelineIO#950]

**Comment by khw7096** [comment]
유투브 경우 i 버튼을 누르면 해당 정보를 담은 modal이 뜬다. 레퍼런스 같이 찾아보기.

**Comment by baesy0** [comment]
### YouTube의 카드 기능
![image](https://user-images.githubusercontent.com/40417084/94509715-da1df380-024f-11eb-9bc8-fa66b803763d.png)

**Comment by baesy0** [comment]
- [ ] 화면 상단에 아이콘 추가
- [x] description가져오는 REST API를 만들기
- [ ] 모달창 만들기
- [ ] 아이콘 클릭하면 모달창 뜨게 만들기

**Comment by khw7096** [comment]
예쁘지않아도 먼저 프리뷰가 될 수 있도록 하기.
