### ISSUE TITLE
사용자 자동 완성: 영어 대소문자 구분 없애기

### ISSUE THREAD

**Issue by baesy0** [digital-idea/OpenPipelineIO#954]
```js
arr[i].searchword.includes(val.toLowerCase()) || arr[i].searchword.includes(val.toUpperCase())
```
위 코드를 추가했을 때 이쁘게 뜨지 않음.
천천히 고민해보기.

**Comment by baesy0** [comment]
### 소문자가 포함되지 않은 경우
![image](https://user-images.githubusercontent.com/40417084/94509381-13a22f00-024f-11eb-9a04-4c5412dae2e5.png)
### 대문자가 포함되지 않은 경우
![image](https://user-images.githubusercontent.com/40417084/94509918-6c25fc00-0250-11eb-9f38-4a561500f15a.png)

**Comment by khw7096** [comment]
위 현상은 버그이다. 코드를 짧게하는 방식으로 버그를 줄인다.
