### ISSUE TITLE
review: canvas 우상단에 아이콘 띄우기

### ISSUE THREAD

**Issue by baesy0** [digital-idea/OpenPipelineIO#965]

**Comment by khw7096** [comment]
어떠한 상황 때문에 이 이슈를 만들었는지 체크하기.

**Comment by baesy0** [comment]
description을 유튜브와 같은 방식으로 표기하기 위해서 생긴 이슈였어요.
지금은 코멘트란 상단에 표기하고 있고, 급한 이슈가 아니니 나중에 디자인을 개선시킬 때 다시 하면 될 거 같아요.
이 이슈는 닫을게요

**Comment by khw7096** [comment]
네~!
